/**
 * This class file was automatically generated by jASN1 v1.11.3-SNAPSHOT (http://www.beanit.com)
 */
package tech.relaycorp.relaynet

import com.beanit.jasn1.ber.BerLength
import com.beanit.jasn1.ber.BerTag
import com.beanit.jasn1.ber.types.BerDateTime
import com.beanit.jasn1.ber.types.BerInteger
import com.beanit.jasn1.ber.types.BerOctetString
import com.beanit.jasn1.ber.types.BerType
import com.beanit.jasn1.ber.types.string.BerVisibleString
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream
import java.io.Serializable

internal class RAMF : BerType, Serializable {
    var recipient: BerVisibleString? = null
    var messageId: BerVisibleString? = null
    var creationTimeUtc: BerDateTime? = null
    var ttl: BerInteger? = null
    var payload: BerOctetString? = null

    @Throws(IOException::class)
    override fun encode(reverseOS: OutputStream): Int {
        return encode(reverseOS, true)
    }

    @Throws(IOException::class)
    fun encode(reverseOS: OutputStream, withTag: Boolean): Int {
        var codeLength = 0
        codeLength += payload!!.encode(reverseOS, false)
        // write tag: CONTEXT_CLASS, PRIMITIVE, 4
        reverseOS.write(0x84)
        codeLength += 1
        codeLength += ttl!!.encode(reverseOS, false)
        // write tag: CONTEXT_CLASS, PRIMITIVE, 3
        reverseOS.write(0x83)
        codeLength += 1
        codeLength += creationTimeUtc!!.encode(reverseOS, false)
        // write tag: CONTEXT_CLASS, PRIMITIVE, 2
        reverseOS.write(0x82)
        codeLength += 1
        codeLength += messageId!!.encode(reverseOS, false)
        // write tag: CONTEXT_CLASS, PRIMITIVE, 1
        reverseOS.write(0x81)
        codeLength += 1
        codeLength += recipient!!.encode(reverseOS, false)
        // write tag: CONTEXT_CLASS, PRIMITIVE, 0
        reverseOS.write(0x80)
        codeLength += 1
        codeLength += BerLength.encodeLength(reverseOS, codeLength)
        if (withTag) {
            codeLength += tag.encode(reverseOS)
        }
        return codeLength
    }

    @Throws(IOException::class)
    override fun decode(`is`: InputStream): Int {
        return decode(`is`, true)
    }

    @Throws(IOException::class)
    fun decode(`is`: InputStream?, withTag: Boolean): Int {
        var codeLength = 0
        var subCodeLength = 0
        val berTag = BerTag()
        if (withTag) {
            codeLength += tag.decodeAndCheck(`is`)
        }
        val length = BerLength()
        codeLength += length.decode(`is`)
        val totalLength = length.`val`
        codeLength += totalLength
        subCodeLength += berTag.decode(`is`)
        if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 0)) {
            recipient = BerVisibleString()
            subCodeLength += recipient!!.decode(`is`, false)
            subCodeLength += berTag.decode(`is`)
        } else {
            throw IOException("Tag does not match the mandatory sequence element tag.")
        }
        if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 1)) {
            messageId = BerVisibleString()
            subCodeLength += messageId!!.decode(`is`, false)
            subCodeLength += berTag.decode(`is`)
        } else {
            throw IOException("Tag does not match the mandatory sequence element tag.")
        }
        if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 2)) {
            creationTimeUtc = BerDateTime()
            subCodeLength += creationTimeUtc!!.decode(`is`, false)
            subCodeLength += berTag.decode(`is`)
        } else {
            throw IOException("Tag does not match the mandatory sequence element tag.")
        }
        if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 3)) {
            ttl = BerInteger()
            subCodeLength += ttl!!.decode(`is`, false)
            subCodeLength += berTag.decode(`is`)
        } else {
            throw IOException("Tag does not match the mandatory sequence element tag.")
        }
        if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.PRIMITIVE, 4)) {
            payload = BerOctetString()
            subCodeLength += payload!!.decode(`is`, false)
            if (subCodeLength == totalLength) {
                return codeLength
            }
        }
        throw IOException("Unexpected end of sequence, length tag: $totalLength, actual sequence length: $subCodeLength")
    }

    companion object {
        private const val serialVersionUID = 1L
        val tag = BerTag(BerTag.UNIVERSAL_CLASS, BerTag.CONSTRUCTED, 16)
    }
}