version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: /
    update_schedule: weekly
  - package_manager: javascript
    directory: /
    update_schedule: weekly
    version_requirement_updates: increase_versions
