name: CI and automatic releases
on:
  pull_request:
  push:
    branches-ignore: [gh-pages]
jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: jacocoTestCoverageVerification

  release:
    needs: ci
#    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish
        env:
          BINTRAY_USERNAME: relaybot
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
