name: CI and automatic releases
on:
  push:
    branches-ignore: [gh-pages]
jobs:
  gradle-wrapper-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

  ci:
    needs: gradle-wrapper-validation
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Test LTS releases
        java: [8, 11]
    name: "java${{ matrix.java }}-${{ matrix.os }}"  # Do not change; used by protected branches
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build dokkaHtml
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: jacocoTestCoverageVerification

  release:
    needs: ci
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Node.js dependencies
        run: npm install

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5'
      - name: Generate docs
        run: |
          # Jekyll docs:
          gem install bundler
          cd docs
          bundle install --path vendor/bundle
          bundle exec jekyll build
          cd ..

          # API docs:
          ./gradlew dokkaHtml

      # Ridiculous workaround for https://github.com/Kotlin/dokka/issues/163
      - name: Move Dokka's assets into a sensible place
        run: |
          set -x -o nounset -o errexit -o pipefail
          mkdir -p ./build/docs
          mv ./build/dokka/html ./build/docs/api
          cd ./build/docs/api
          mv ./styles ./images ./scripts navigation.html index.html ./awala/
          find ./awala/ -name '*.html' -print0 | xargs -0 sed -i 's;../styles/;styles/;g'
          find ./awala/ -name '*.html' -print0 | xargs -0 sed -i 's;../images/;images/;g'
          find ./awala/ -name '*.html' -print0 | xargs -0 sed -i 's;../scripts/;scripts/;g'
          find ./awala/ -name '*.html' -print0 | xargs -0 sed -i 's;pathToRoot = "../;pathToRoot = ";g'
          sed -i 's;href="awala/;href=";g' ./awala/navigation.html

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_CENTRAL_SIGNING_KEY_PASSPHRASE }}

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          publish_branch: gh-pages
          publish_dir: ./build/docs
          allow_empty_commit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
